version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - TEMPORAL_ADDRESS=temporal:7233
    volumes:
      - temporal-data:/var/temporal

  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=*
    depends_on:
      - temporal

volumes:
  temporal-data: